name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest 'https://2009.filemail.com/api/file/get?filekey=JdX6kwxtENTNUtzP5LyGa9T70bEJEIpscoaD_UcLfo9qnirar_mvLpSDUa0&pk_vid=e198dae3b7b8fd5d17257174852f9b9c' -OutFile playit.exe
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Run Tunnel
      env:
        SUPER_SECRET: ${{ secrets.secret }}
      run: .\playit.exe --secret "$env:SUPER_SECRET"
