name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest 'https://2009.filemail.com/api/file/get?filekey=Rk9enZ_6iQxS0lQJgEh4Gr--eWNKP1iTr9GhYmHHYgTsSepXmDs3521pc8o&pk_vid=711b5a2653a0707917208960702e17de' -OutFile playit.exe
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Run Tunnel
      run: .\playit.exe --secret dbb1130e024ec135e9f356c0fffdbdc4406045e89732017e709115767bfc0f09
